### ISSUE TITLE
How would i remove some choices of skins?

### ISSUE THREAD

**Issue by ForthtuN** [ESX-Org/esx_skin#17]
So, i don't want players to get vests, watches, chains, masks when they make their character since those things they can get in the shops, also the bulletproof vest even tho it doesen't add armor people can make misstakes and think they are the real deal.

So how could i hide those options in the menu and also make watches and helmets use value -1?

**Comment by ElPumpo** [comment]
See how eg esx_barbershop parses arguments to only let some items be shown
