### ISSUE TITLE
Memory usage!!

### ISSUE THREAD

**Issue by benzon** [ESX-Org/esx_skin#19]
The current memory ussage of esx_skin is not good sorry to say.

It uses 50mb+ with out reason, not EUP cloath or what so ever.

**Comment by benzon** [comment]
it's not the skin resource thats the issue, the issue is actually esx_menu_default i guess, after replacing with an old version that gives the warning, of ms usage, there is no issue or what so ever with memory usage.

**Comment by SLuuuuuuG** [comment]
Which version of the esx_menu_default did you find that works and does not display that message

**Comment by ElPumpo** [comment]
Duplicate of #16
