### ISSUE TITLE
ESX_SKIN problem while logging to server

### ISSUE THREAD

**Issue by MaldoNanoche** [ESX-Org/esx_skin#20]
![image](https://user-images.githubusercontent.com/45569776/52225997-139c3100-28ac-11e9-86a6-4b2a9e24ef09.png)
Nothing show up while connecting to server ;x

**Comment by Erkan0** [comment]
I get the same error and it says something with es_extended with  this shit ''ESX.UI.Menu.RegisteredTypes[type].open(namespace, name, data)''

**Comment by Erkan0** [comment]
That's because you don't have esx menus lol
