### ISSUE TITLE
ESX Not saving skin on leaving / joining

### ISSUE THREAD

**Issue by VortexLife** [ESX-Org/esx_skin#25]
I am having issues with esx not saving skins on leaving, when they join back it sets it back to default
skin with (BLOB) in the database, is there anyway to fix this issue as it doesn't reset on death.

**Comment by sefuo** [comment]
how did you fix it ? i got same problem

**Comment by latezz22** [comment]
fuck mee too

**Comment by KaoticChaos** [comment]
anyone ever fix this?

**Comment by SienkoV2** [comment]
did you fave fixe this ??????

**Comment by THEMARCE** [comment]
how do i fix it i have the same problem please
