### ISSUE TITLE
[HELP] Disable fixed camera

### ISSUE THREAD

**Issue by vitorotero** [ESX-Org/esx_skin#27]
How do I disable the fixed camera?
I want to move the camera with the mouse and not number pad 4 and 6..

Thanks

**Comment by KoolAiddTV** [comment]
hey man you ever figure this out?

**Comment by XvenDeR** [comment]
good idea, gotta look in to this

**Comment by XvenDeR** [comment]
client/main.lue

74 line, comment these.

```
CreateSkinCam()
zoomOffset = _components[1].zoomOffset
camOffset = _components[1].camOffset
```
