### ISSUE TITLE
[Need HELP] Erreur on console

### ISSUE THREAD

**Issue by Ilian0112** [ESX-Org/esx_skin#31]
**Hi !**
I have a problem with esx_skin, when I run my server the script puts a console error every time someone connects and this error prevents load the skin.

> The mistake :

```
SCRIPT ERROR: @ esx_skin / server / main.lua: 47: attempt to index a nil value (local 'user')
> ref (@ esx_skin / server / main.lua: 47)
> setImmediate (@ mysql-async / mysql-async.js: 14431)
```
 Namely, everything worked well there is 4 days and when I wanted to add the double job it was the drama more nothing worked suddenly I try to re-install ALL the server scripts & the database but nothing works so that's why I turn to you.

_Thank you to those who will help me and thank you for taking the time to read._

**Comment by TrickzzEU** [comment]
Mine had this but it fixed over night.
