### ISSUE TITLE
Esx skin error	xPlayer.setMaxWeight(defaultMaxWeight)

### ISSUE THREAD

**Issue by kekev2001** [ESX-Org/esx_skin#32]
SCRIPT ERROR: @esx_skin/server/main.lua:14: attempt to call a nil value (field 'setMaxWeight')
![Knipsel](https://user-images.githubusercontent.com/56051728/67681333-69aa8a80-f98d-11e9-8de0-7267d349a405.PNG)

**Comment by CALauer** [comment]
Also have this issue.

**Comment by CALauer** [comment]
HotFix - I made a duplicate of my server only reinstalling es_extended and that fixed my issue. Hope this helps.

**Comment by sisanc6** [comment]
SCRIPT ERROR: @esx_skin/server/main.lua:14: attempt to call a nil value (field 'setMaxWeight')
https://i.imgur.com/DmlCJLM.png

**Comment by 2ratheflouterman** [comment]
> SCRIPT ERROR: @esx_skin/server/main.lua:14: attempt to call a nil value (field 'setMaxWeight')
> https://i.imgur.com/DmlCJLM.png

Did you fix it ?

**Comment by 32minds** [comment]
fixed?
