### ISSUE TITLE
SCRIPT ERROR: @esx_skin/server/main.lua:14: attempt to call a nil value (field 'setMaxWeight')

### ISSUE THREAD

**Issue by StyXiu** [ESX-Org/esx_skin#36]
Hello, i have a problem with this resource, i tryied to reinstalled esx_skin and skinchanger, but doesnt helped.
![image](https://user-images.githubusercontent.com/56841176/72377808-7b8c0600-3710-11ea-86dc-9403349232a9.png)
Someone know how to fix it?

**Comment by Wiinsa** [comment]
I have the same error with esx_skin and esx_addonaccount. Let me know if you fix it.

**Comment by themadscientistcreations** [comment]
im trying to figure this out as well if i manager to get it i will report back i swear.
