### ISSUE TITLE
Option to add /reskin to open the skin menu for other players.

### ISSUE THREAD

**Issue by TheBiggestSmoke** [ESX-Org/esx_skin#37]
I was wondering if there was a way to give admins the ability to open the skin menu for other players?

**Comment by BuLLeTLG** [comment]
TriggerEvent('es:addGroupCommand', 'reskin', "admin", function(source, args, user)
	if args[1] then
		if(tonumber(args[1]) and GetPlayerName(tonumber(args[1])))then
			local player = tonumber(args[1])

			-- User permission check
			TriggerEvent("es:getPlayerFromId", player, function(target)

				local reason = args
				table.remove(reason, 1)
				if(#reason == 0)then
					reason = "You have received a reskin."
				else
					reason = "Reskin: " .. table.concat(reason, " ")
				end
				TriggerClientEvent('esx_skin:openSaveableMenu', player)
			end)
		else
			TriggerClientEvent('chat:addMessage', source, { args = {"^1SYSTEM: ", "Incorrect player ID"}})
		end
	else
		TriggerClientEvent('chat:addMessage', source, { args = {"^1SYSTEM: ", "Incorrect player ID"}})
	end
end)

**Comment by TheBiggestSmoke** [comment]
Thanks, Been ripping my hair out over this.
