### ISSUE TITLE
esx_skin is not saving in es_extended my skin when i disconnect and when i create skin too

### ISSUE THREAD

**Issue by honzek12345** [ESX-Org/esx_skin#59]
Can anyone help me ?

**Comment by MoonDawnGames** [comment]
Same here. Really frustrating...

**Comment by kango76** [comment]
Same issue

**Comment by MoonDawnGames** [comment]
Guys best thing to do is to revert back to an older version. I did so and it has sorted my problem. Hope this helps

**Comment by honzek12345** [comment]
Yes it is working thanks.

**Comment by imartinezgregori** [comment]
@honzek12345 @MoonDawnGames older version of esx_skin or es_extended??
