### ISSUE TITLE
Is database missing?

### ISSUE THREAD

**Issue by hacklover** [ESX-Org/esx_skin#9]
There is no esx_skin.sql

**Comment by chasen-bettinger** [comment]
I am not sure if that is a mistake or not, but I couldn't find that database in their entire repository's history.

**Comment by chasen-bettinger** [comment]
You are right. That database is nowhere to be found.

**Comment by hacklover** [comment]
For now you can use version 1.0.0 without .sql
https://github.com/ESX-Org/esx_skin/tree/1.0.0

**Comment by ElPumpo** [comment]
Install ESX correctly
